CREATE WAREHOUSE IF NOT EXISTS WH_ETL
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE WH_ETL;

CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;

CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.RAW;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.CLEAN;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.DWH;
CREATE SCHEMA IF NOT EXISTS AIRLINE_DWH.AUDIT;