USE DATABASE AIRLINE_DWH;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT AIRLINE_DWH.RAW.FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE STAGE AIRLINE_DWH.RAW.STG_AIRLINE
  FILE_FORMAT = AIRLINE_DWH.RAW.FF_CSV;