CREATE ROW ACCESS POLICY IF NOT EXISTS AIRLINE_DWH.DWH.RAP_COUNTRY_ACCESS
AS (country_name VARCHAR)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE
        WHEN CURRENT_ROLE() = 'ANALYST_GEORGIA' AND country_name = 'Georgia' THEN TRUE
        WHEN CURRENT_ROLE() = 'ANALYST_FRANCE' AND country_name = 'France' THEN TRUE
        ELSE FALSE
    END;