CREATE OR REPLACE SECURE VIEW AIRLINE_DWH.DWH.VW_FACT_TRAVEL_SECURE 
WITH ROW ACCESS POLICY AIRLINE_DWH.DWH.RAP_COUNTRY_ACCESS ON (COUNTRY_NAME)
AS
SELECT
    f.TRAVEL_FACT_KEY,
    f.ROW_ID,
    f.PASSENGER_KEY,
    p.PASSENGER_ID,
    p.FIRST_NAME,
    p.LAST_NAME,
    p.GENDER,
    p.AGE,
    p.NATIONALITY,
    f.AIRPORT_KEY,
    a.AIRPORT_NAME,
    a.AIRPORT_COUNTRY_CODE,
    a.COUNTRY_NAME,
    a.AIRPORT_CONTINENT,
    a.CONTINENTS,
    f.ARRIVAL_AIRPORT_KEY,
    aa.ARRIVAL_AIRPORT,
    f.PILOT_KEY,
    pi.PILOT_NAME,
    f.TICKET_TYPE_KEY,
    tt.TICKET_TYPE,
    f.STATUS_KEY,
    s.FLIGHT_STATUS,
    s.PASSENGER_STATUS,
    f.DEPARTURE_DATE_KEY,
    d.FULL_DATE AS DEPARTURE_DATE,
    d.YEAR,
    d.MONTH,
    d.DAY
FROM AIRLINE_DWH.DWH.FACT_TRAVEL f
JOIN AIRLINE_DWH.DWH.DIM_PASSENGER p
    ON f.PASSENGER_KEY = p.PASSENGER_KEY
JOIN AIRLINE_DWH.DWH.DIM_AIRPORT a
    ON f.AIRPORT_KEY = a.AIRPORT_KEY
JOIN AIRLINE_DWH.DWH.DIM_ARRIVAL_AIRPORT aa
    ON f.ARRIVAL_AIRPORT_KEY = aa.ARRIVAL_AIRPORT_KEY
JOIN AIRLINE_DWH.DWH.DIM_PILOT pi
    ON f.PILOT_KEY = pi.PILOT_KEY
JOIN AIRLINE_DWH.DWH.DIM_TICKET_TYPE tt
    ON f.TICKET_TYPE_KEY = tt.TICKET_TYPE_KEY
JOIN AIRLINE_DWH.DWH.DIM_STATUS s
    ON f.STATUS_KEY = s.STATUS_KEY
LEFT JOIN AIRLINE_DWH.DWH.DIM_DATE d
    ON f.DEPARTURE_DATE_KEY = d.DATE_KEY;