USE DATABASE AIRLINE_DWH;
USE SCHEMA CLEAN;

CREATE OR REPLACE TABLE AIRLINE_DWH.CLEAN.TRAVEL_CLEAN (
    ROW_ID NUMBER(5,0),
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR
);