USE DATABASE AIRLINE_DWH;
USE SCHEMA DWH;

CREATE OR REPLACE TABLE DWH.DIM_DATE (
  DATE_KEY        NUMBER AUTOINCREMENT,
  FULL_DATE       DATE,
  YEAR            NUMBER,
  MONTH           NUMBER,
  DAY             NUMBER
);

CREATE OR REPLACE TABLE DWH.DIM_PASSENGER (
  PASSENGER_KEY   NUMBER AUTOINCREMENT,
  PASSENGER_ID    VARCHAR,
  FIRST_NAME      VARCHAR,
  LAST_NAME       VARCHAR,
  GENDER          VARCHAR,
  AGE             VARCHAR,
  NATIONALITY     VARCHAR
);

CREATE OR REPLACE TABLE DWH.DIM_AIRPORT (
  AIRPORT_KEY           NUMBER AUTOINCREMENT,
  AIRPORT_NAME          VARCHAR,
  AIRPORT_COUNTRY_CODE  VARCHAR,
  COUNTRY_NAME          VARCHAR,
  AIRPORT_CONTINENT     VARCHAR,
  CONTINENTS            VARCHAR
);

CREATE OR REPLACE TABLE DWH.DIM_ARRIVAL_AIRPORT (
  ARRIVAL_AIRPORT_KEY   NUMBER AUTOINCREMENT,
  ARRIVAL_AIRPORT       VARCHAR
);

CREATE OR REPLACE TABLE DWH.DIM_PILOT (
  PILOT_KEY       NUMBER AUTOINCREMENT,
  PILOT_NAME      VARCHAR
);

CREATE OR REPLACE TABLE DWH.DIM_TICKET_TYPE (
  TICKET_TYPE_KEY NUMBER AUTOINCREMENT,
  TICKET_TYPE     VARCHAR
);

CREATE OR REPLACE TABLE DWH.DIM_STATUS (
  STATUS_KEY        NUMBER AUTOINCREMENT,
  FLIGHT_STATUS     VARCHAR,
  PASSENGER_STATUS  VARCHAR
);