USE DATABASE AIRLINE_DWH;
USE SCHEMA DWH;

CREATE OR REPLACE TABLE DWH.FACT_TRAVEL (
  TRAVEL_FACT_KEY        NUMBER AUTOINCREMENT,
  ROW_ID                 VARCHAR,
  PASSENGER_KEY          NUMBER,
  AIRPORT_KEY            NUMBER,
  ARRIVAL_AIRPORT_KEY    NUMBER,
  PILOT_KEY              NUMBER,
  TICKET_TYPE_KEY        NUMBER,
  STATUS_KEY             NUMBER,
  DEPARTURE_DATE_KEY     NUMBER
); 