USE DATABASE AIRLINE_DWH;
USE SCHEMA AUDIT;

CREATE OR REPLACE TABLE AUDIT.ETL_LOG (
  RUN_ID         VARCHAR,
  PROC_NAME      VARCHAR,
  TARGET_TABLE   VARCHAR,
  ACTION_TYPE    VARCHAR,
  ROWS_AFFECTED  NUMBER,
  STARTED_AT     TIMESTAMP_NTZ,
  ENDED_AT       TIMESTAMP_NTZ,
  STATUS         VARCHAR,
  ERROR_MESSAGE  VARCHAR
);