USE DATABASE AIRLINE_DWH;
USE SCHEMA DWH;

INSERT INTO DWH.DIM_PASSENGER
  (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)
SELECT DISTINCT
  PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY
FROM CLEAN.TRAVEL_CLEAN;

INSERT INTO DWH.DIM_AIRPORT
  (AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS)
SELECT DISTINCT
  AIRPORT_NAME, AIRPORT_COUNTRY_CODE, COUNTRY_NAME, AIRPORT_CONTINENT, CONTINENTS
FROM CLEAN.TRAVEL_CLEAN;

INSERT INTO DWH.DIM_PILOT (PILOT_NAME)
SELECT DISTINCT PILOT_NAME
FROM CLEAN.TRAVEL_CLEAN;

INSERT INTO DWH.DIM_TICKET_TYPE (TICKET_TYPE)
SELECT DISTINCT TICKET_TYPE
FROM CLEAN.TRAVEL_CLEAN;

INSERT INTO DWH.DIM_STATUS (FLIGHT_STATUS, PASSENGER_STATUS)
SELECT DISTINCT FLIGHT_STATUS, PASSENGER_STATUS
FROM CLEAN.TRAVEL_CLEAN;

INSERT INTO DWH.DIM_ARRIVAL_AIRPORT (ARRIVAL_AIRPORT)
SELECT DISTINCT ARRIVAL_AIRPORT
FROM CLEAN.TRAVEL_CLEAN;

INSERT INTO DWH.DIM_DATE (FULL_DATE, YEAR, MONTH, DAY)
SELECT DISTINCT
  DEPARTURE_DATE,
  YEAR(DEPARTURE_DATE),
  MONTH(DEPARTURE_DATE),
  DAY(DEPARTURE_DATE)
FROM CLEAN.TRAVEL_CLEAN
WHERE DEPARTURE_DATE IS NOT NULL;