USE DATABASE AIRLINE_DWH;
USE SCHEMA DWH;

INSERT INTO DWH.FACT_TRAVEL (
  ROW_ID,
  PASSENGER_KEY,
  AIRPORT_KEY,
  ARRIVAL_AIRPORT_KEY,
  PILOT_KEY,
  TICKET_TYPE_KEY,
  STATUS_KEY,
  DEPARTURE_DATE_KEY
)
SELECT
  c.ROW_ID,
  p.PASSENGER_KEY,
  a.AIRPORT_KEY,
  aa.ARRIVAL_AIRPORT_KEY,
  pi.PILOT_KEY,
  t.TICKET_TYPE_KEY,
  s.STATUS_KEY,
  d.DATE_KEY
FROM CLEAN.TRAVEL_CLEAN c
JOIN DWH.DIM_PASSENGER p
  ON p.PASSENGER_ID = c.PASSENGER_ID
JOIN DWH.DIM_AIRPORT a
  ON a.AIRPORT_NAME = c.AIRPORT_NAME
 AND a.AIRPORT_COUNTRY_CODE = c.AIRPORT_COUNTRY_CODE
JOIN DWH.DIM_ARRIVAL_AIRPORT aa
  ON aa.ARRIVAL_AIRPORT = c.ARRIVAL_AIRPORT
JOIN DWH.DIM_PILOT pi
  ON pi.PILOT_NAME = c.PILOT_NAME
JOIN DWH.DIM_TICKET_TYPE t
  ON t.TICKET_TYPE = c.TICKET_TYPE
JOIN DWH.DIM_STATUS s
  ON s.FLIGHT_STATUS = c.FLIGHT_STATUS
 AND s.PASSENGER_STATUS = c.PASSENGER_STATUS
LEFT JOIN DWH.DIM_DATE d
  ON d.FULL_DATE = c.DEPARTURE_DATE;